In [1]:
import numpy as np

In [2]:
d1 = np.array([1, 2])
d1

array([1, 2])

In [3]:
d2 = np.array([[1, 2], [3, 4], [5, 6]])
d2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
d3 = np.array([[[1, 2], [3, 4]],
               [[5, 6], [7, 8]],
               [[9, 10], [11, 12]]
              ])
d3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [5]:
d1.shape

(2,)

In [6]:
d2.shape

(3, 2)

In [7]:
d3.shape

(3, 2, 2)

In [8]:
d3.ndim

3

In [9]:
d3.dtype

dtype('int64')

In [10]:
d3.size

12

In [11]:
type(d3)

numpy.ndarray

In [12]:
import pandas as pd

# pandas can only process 2d and 1d
df = pd.DataFrame(d2)
df

0  1
0  1  2
1  3  4
2  5  6

In [13]:
zeros = np.zeros((3,2))
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [15]:
random_array = np.random.randint(0, 10, (5,5))
random_array

array([[2, 5, 7, 6, 0],
       [6, 1, 4, 5, 2],
       [4, 4, 3, 2, 5],
       [6, 4, 1, 3, 2],
       [9, 4, 6, 5, 6]], dtype=int32)

In [16]:
random_array_2 = np.random.random((5, 5))
random_array_2

array([[0.08387666, 0.01546309, 0.43136878, 0.58658026, 0.33722445],
       [0.67180133, 0.33971941, 0.32275557, 0.36199044, 0.37263062],
       [0.12372398, 0.40994379, 0.53997108, 0.94842955, 0.53362991],
       [0.99478373, 0.72029301, 0.05134521, 0.9312745 , 0.33174005],
       [0.57870113, 0.71879164, 0.96103676, 0.55282709, 0.97466585]])

In [17]:
# Pseudo-random
np.random.seed(0)

random_array_3 = np.random.randint(10, size=(3,2))
random_array_3

array([[5, 0],
       [3, 3],
       [7, 9]], dtype=int32)

In [18]:
np.unique(random_array)

array([0, 1, 2, 3, 4, 5, 6, 7, 9], dtype=int32)

In [19]:
d3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [20]:
d3[:, :, 0]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

## Manipulating data

In [21]:
random_array_3 * d1 

array([[ 5,  0],
       [ 3,  6],
       [ 7, 18]])

In [22]:
random_array_3 * d2

array([[ 5,  0],
       [ 9, 12],
       [35, 54]])

In [23]:
np.square(d1)

array([1, 4])

In [24]:
d1 ** 2

array([1, 4])

In [25]:
np.exp(d1)

array([2.71828183, 7.3890561 ])

## Aggregation

In [26]:
%timeit np.sum(d2)

6.33 μs ± 123 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [27]:
np.mean(d2)

np.float64(3.5)

In [28]:
np.var(d2)

np.float64(2.9166666666666665)

In [29]:
np.std(d2)

np.float64(1.707825127659933)

## Reshaping & Transposing

In [30]:
d2.shape

(3, 2)

In [31]:
d2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
reshaped_d2 = d2.reshape(3, 2, 1)

In [33]:
reshaped_d2 * d3

array([[[ 1,  2],
        [ 6,  8]],

       [[15, 18],
        [28, 32]],

       [[45, 50],
        [66, 72]]])

In [34]:
# Tranpose = flip axis
d3.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

## Dot product

In [35]:
matrix1 = np.random.randint(10, size=(3,5))
matrix2 = np.random.randint(10, size=(3,5))

In [36]:
# Element-wise multiplication
matrix1 * matrix2

array([[27, 40, 18, 16, 21],
       [ 0, 24, 40,  0, 12],
       [21, 56,  8,  3, 15]], dtype=int32)

In [37]:
# Dot product
# 3x5 . 5x3 = 3x3
np.dot(matrix1, matrix2.T)

array([[122,  39,  84],
       [212,  76, 111],
       [210,  71, 103]], dtype=int32)

## Comparision

In [38]:
d1 >= d2

array([[ True,  True],
       [False, False],
       [False, False]])

## Sorting

In [39]:
random_array_2

array([[0.08387666, 0.01546309, 0.43136878, 0.58658026, 0.33722445],
       [0.67180133, 0.33971941, 0.32275557, 0.36199044, 0.37263062],
       [0.12372398, 0.40994379, 0.53997108, 0.94842955, 0.53362991],
       [0.99478373, 0.72029301, 0.05134521, 0.9312745 , 0.33174005],
       [0.57870113, 0.71879164, 0.96103676, 0.55282709, 0.97466585]])

In [40]:
np.sort(random_array_2)

array([[0.01546309, 0.08387666, 0.33722445, 0.43136878, 0.58658026],
       [0.32275557, 0.33971941, 0.36199044, 0.37263062, 0.67180133],
       [0.12372398, 0.40994379, 0.53362991, 0.53997108, 0.94842955],
       [0.05134521, 0.33174005, 0.72029301, 0.9312745 , 0.99478373],
       [0.55282709, 0.57870113, 0.71879164, 0.96103676, 0.97466585]])

In [41]:
# Return arr of indicies sorted by value
np.argsort(random_array_2)

array([[1, 0, 4, 2, 3],
       [2, 1, 3, 4, 0],
       [0, 1, 4, 2, 3],
       [2, 4, 1, 3, 0],
       [3, 0, 1, 2, 4]])

In [42]:
np.argmax(random_array_2, axis=0)

array([3, 3, 4, 2, 4])

## Image

<img src="images/arctic-fox.jpg">

In [43]:
from matplotlib.image import imread

arctic_fox = imread("images/arctic-fox.jpg")
arctic_fox

array([[[105,  89,  55],
        [ 95,  79,  46],
        [102,  86,  53],
        ...,
        [154, 129,  89],
        [156, 129,  86],
        [159, 132,  89]],

       [[105,  89,  53],
        [ 98,  82,  48],
        [103,  87,  53],
        ...,
        [161, 138,  96],
        [157, 130,  85],
        [155, 126,  84]],

       [[102,  87,  48],
        [ 97,  81,  45],
        [101,  85,  49],
        ...,
        [161, 140,  97],
        [153, 129,  83],
        [158, 129,  85]],

       ...,

       [[ 41,  29,  15],
        [ 37,  25,   9],
        [ 42,  31,  13],
        ...,
        [153, 153, 155],
        [149, 149, 151],
        [155, 155, 155]],

       [[ 44,  32,  18],
        [ 38,  26,  10],
        [ 35,  23,   7],
        ...,
        [150, 149, 154],
        [148, 148, 150],
        [153, 153, 155]],

       [[ 49,  37,  23],
        [ 30,  21,   6],
        [ 30,  21,   4],
        ...,
        [137, 138, 143],
        [147, 148, 152],
        [153, 154, 158]]

In [44]:
np.max(arctic_fox, axis=0)

array([[180, 184, 188],
       [177, 180, 185],
       [178, 181, 186],
       ...,
       [215, 201, 200],
       [216, 209, 200],
       [219, 209, 206]], shape=(1600, 3), dtype=uint8)

In [45]:
type(arctic_fox)

numpy.ndarray